### ISSUE TITLE
Masked textbox?

### ISSUE THREAD

**Issue by foxt** [ssight/native-prompt#1]
Is it possible to get a masked text box in this library? I only need support for macOS for this feature

**Comment by ssight** [comment]
That's not currently supported, but if you just want to authenticate the user, you can try using [os-auth](https://github.com/ssight/os-auth) in the meantime. 

I'll be sure to begin work on true masked text boxes though, and I'll update you when it's done.

**Comment by ssight** [comment]
@theLMGN Version 2.x now supports masked textboxes, and it supports all three OSes.

If there's anything else you'd like to ask, be sure to let me know.
